# Introduction to Numpy

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/Users/dusisarathchandra/miniconda3/envs/env/lib/python3.11/site-packages/numpy/__init__.py'>

## Creating Arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a[2]

3

In [9]:
range_array = np.arange(10)

In [10]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
r_array = np.arange(3,12)
r_array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

## Multi-dimentional Arrays

In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr[1][2]

6

In [19]:
arr[1,2] = 20

In [20]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 20],
       [ 7,  8,  9]])

In [22]:
# Gets row by row_id
arr[1]

array([ 4,  5, 20])

In [23]:
# assign an array to a row
arr[1] = np.array([10, 11, 12])

In [24]:
arr

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [27]:
# Get column by column_id
arr[:, 1]

array([ 2, 11,  8])

## Generate Random arrays

In [31]:
np.random.seed(3)
np.random.rand(5,2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761],
       [0.89294695, 0.89629309],
       [0.12558531, 0.20724288],
       [0.0514672 , 0.44080984]])

### Generate random array following Normal distribution

In [33]:
np.random.seed(12)
np.random.randn(5,2)

array([[ 0.47298583, -0.68142588],
       [ 0.2424395 , -1.70073563],
       [ 0.75314283, -1.53472134],
       [ 0.00512708, -0.12022767],
       [-0.80698188,  2.87181939]])

### Generate random integer array within a specific range

In [34]:
np.random.randint(0, 10, (5,2))

array([[2, 6],
       [2, 0],
       [4, 6],
       [9, 0],
       [0, 9]])